<!--Not Used! I suggest deleting-->

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="./../css/bootstrap.css">
    <link rel="stylesheet" href="./../css/style.css">

</head>
<body>
<main class="container">

    <div class="row">
        <nav class="navbar navbar-toggleable-md navbar-inverse">

            <a href="/BeeWebpage/public" class="navbar-brand text-primary" id="logo">
                <img src="./../images/logo.png" width="100px" height="100px">
            </a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-primary" id="log_out_button" href="#"> Odhlasenie</a>

                    </li>
                    <li>
                        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        <a id = "logged-in-user"> </a>
                    </li>
                </ul>
            </div>

        </nav>
    </div>

    <div class="row">
        <div class="col-12 col-sm-8 col-md-8 col-lg-8 col-xl-8">
        </div>

        <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4">
            <section id="search">
                <label for="search-input">
                    <i class="fa fa-search" aria-hidden="true"></i>
                    <span class="sr-only"></span>
                </label>
                <input id="search-input" class="form-control input-lg" autocomplete="off" spellcheck="false" autocorrect="off" tabindex="1">
                <a id="search-clear" href="#" class="fa fa-times-circle hide" aria-hidden="true">
                    <span class="sr-only">Clear search</span>
                </a>
            </section>
            <div id = "filter">
                <i class="fa fa-filter" aria-hidden="true"></i>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4">
            <p>Notifikacie</p>
            <!--Example of notifications fields-->

            <div class = "notification">
                <a class = "delete-notification" href="#">x</a>
            </div>
            <div class = "notification">
                <a class = "delete-notification" href="#">x</a>
            </div>
            <div class = "notification">
                <a class = "delete-notification" href="#">x</a>
            </div>
        </div>
        <div class="col-12 col-sm-8 col-md-8 col-lg-8 col-xl-8">
            <a id = "add-apiary" href="#"><i class="fa fa-plus-square" aria-hidden="true"></i></a>
            <?php foreach ($devices as $device): ?>
            <div class = "device">
                <p> cas: <?=$device[0]['cas']?> </p>
                
                <ul>
                <?php foreach ($device as $device_data): ?>
                    <li> TYP: <?=$device_data['typ']?> HODNOTA: <?=$device_data['hodnota'] ?> </li>
                <?php endforeach; ?>
                </ul>
            </div>
            <?php endforeach; ?>
        </div>
    </div>

</main>

<?php echo $footer;?>


<!-- Optional JavaScript -->

<script src="./../js/jquery.min.js"></script>
<script src="./../js/tether.min.js"></script>
<script src="./../js/bootstrap.min.js"></script>
<script src="./../js/style.js"></script>
</body>
</html>
