
<?php

	$errName ="";
    $errMessage ="";
	$errEmail ="";
	$errPhone ="";
	if (isset($_POST['submit'])) {
		$name = $_POST['name'];
		$email = $_POST['mail'];
		$phone = $_POST['phone'];
		
		if (!preg_match("/^[a-zA-Z á Á ä č Č ď Ď dž Dž é É í ĺ ľ Ľ ó Ó ó š Š ť Ť ú Ú ň Ň ý ž Ž ]*$/",$name) || (!$_POST['name'])) {
			$errName = "Zadali ste nesprávny formát mena! (príklad: Janko Mrkvička)";
		}
		
		  if (!$_POST['mail'] || !filter_var($_POST['mail'], FILTER_VALIDATE_EMAIL)) {
			$errEmail = 'Zadali ste neplatný e-mail! (príklad: moj@mail.com)';
		}
		
		if (!preg_match("/^[0-9]*$/",$phone) || (!$_POST['phone'])) {
			$errPhone = "Zadali ste nesprávny formát telefónneho čísla! (príklad: 0905123456)";
		}
	
	if (!$errName && !$errEmail && !$errPhone)
	{
		$ma = "";
		$subject = 'KONTAKT Včeličky Team';
		$result = 'Kontaktný formulár';
		$text = $_POST["message"];
		$ma = $_POST["mail"];
		$prem=0;

		$poa = '<html><body>';
		$poa .= '<table rules="all" style="border-color: #666;" cellpadding="10">';
		$poa .= "<tr style='background: #eee;'><td><strong>Meno:</strong> </td><td>" . strip_tags($_POST['name']) . "</td></tr>";
		$poa .= "<tr><td><strong>E-mail:</strong> </td><td>" . strip_tags($_POST['mail']) . "</td></tr>";
		$poa .= "<tr><td><strong>Telefón:</strong> </td><td>" . strip_tags($_POST['phone']) . "</td></tr>";
		$poa .= "<tr><td><strong>Odkaz:</strong> </td><td>" . strip_tags($_POST['message']) . "</td></tr>";
		$poa .= "</table>";
		$poa .= "</body></html>";
		$headers  = "MIME-Version: 1.0" . PHP_EOL;
		$headers .= "Content-Type: text/html; charset=utf-8" . PHP_EOL;
		$headers .= "From: WEB-Včeličky Team" . PHP_EOL;

if ( Mail("sosnak.matus@gmail.com  ", $result, $poa, $headers) )
{
	echo '<script language="javascript">';
	echo 'alert("Mail bol úspešne odoslaný")';
	echo '</script>';
	
}
else 
{
	echo '<script language="javascript">';
	echo 'alert("Mail sa nepodarilo odoslať")';
	echo '</script>';
}
		
    }
		
  }
?>


<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="shortcut icon" href="images/avicon.ico">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/global.css">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top bg-faded">
    <a href="/BeeWebpage/public" class="navbar-brand text-primary" id="logo" style="margin-left: 10%">
        <img src="images/logo.png" width="50px" height="50px">
    </a>

    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <!--                        <ul class="navbar-nav">-->
        <ul class="navbar-nav ml-auto">
            <?php foreach($menu as $key => $value): ?>

                <li class="nav-item">
                    <a class="nav-link"
                       href="<?=$value['href']?>"
                        <?php if(strlen($value['href']) == 0): echo 'data-toggle="modal" data-target="#ModalLoginForm"'; endif; ?>
                    >
                        <?=$value['name']?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

</nav>

<div style="margin-top: 40px">
    <section id="contact">
        <div class="container">
            <div class="well well-sm">
                <h3><strong>Kontaktujte nás</strong></h3>
            </div>


            <div class="row">
                <div class="col-md-7">
                    <iframe src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJqfPweeyLbEcRYOgK_ClSWIs&key=AIzaSyAb0c6De0ni1ZJZrdWH-hz3KD-MWLD8hY0" width="100%" height="315" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>

                <div class="col-md-5">
                    <h4><strong>Zadajte údaje</strong></h4>
                    <form action="" method="POST">
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" value="<?php if (isset($_POST['name'])){ echo htmlspecialchars($_POST['name']); } ?>" placeholder="Meno">
							<?php echo "<p class='text-danger'>$errName</p>";?>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="mail" value="<?php if (isset($_POST['email'])){ echo htmlspecialchars($_POST['mail']); } ?>" placeholder="E-mail">
							<?php echo "<p class='text-danger'>$errEmail</p>";?>
                        </div>
                        <div class="form-group">
                            <input type="tel" class="form-control" name="phone" value="<?php if (isset($_POST['email'])){ echo htmlspecialchars($_POST['phone']); } ?>" placeholder="Telefón">
							<?php echo "<p class='text-danger'>$errPhone</p>";?>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="message" rows="3" placeholder="Správa"></textarea>
                        </div>
                        <button class="btn btn-default" type="submit" name="submit">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i> Odoslať
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Modal HTML Markup -->
    <div id="ModalLoginForm" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title text-xs-center">Prihlásenie</h4>
                </div>
                <div class="modal-body">
                    <form role="form" id = "login">
                        <div class="form-group">
                            <label class="control-label">Email</label>
                            <div>
                                <input type="email" class="form-control input-lg" name="email" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Heslo</label>
                            <div>
                                <input type="password" class="form-control input-lg" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember"> Zapamätaj si
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <a class="btn btn-link" href="">Zabudli ste heslo?</a>
                                <button type="button" id = "login_button" class="btn btn-info btn-block">Prihlásiť sa</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer text-xs-center">
                    Nemáte účet? <br><a href="/BeeWebpage/public/register"> Zaregistrujte sa »</a>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->



    <?php echo $footer;?>
    <script src="js/jquery.min.js"></script>
    <script src="js/tether.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
    <script src="js/form_validate.js"></script>
    <script src="js/style.js"></script>

</body>
</html>

