<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta http-equiv="x-ua-compatible" content="ie=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="css/bootstrap.css">
<!--        <link rel="stylesheet" href="css/style.css">-->
        <link href="css/global.css" rel="stylesheet">

    </head>
    <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-faded fixed-top">

        <a href="/public" class="navbar-brand text-primary" id="logo" style="margin-left: 10%">
            <img src="images/logo.png" width="50px" height="50px">
        </a>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <!--                        <ul class="navbar-nav">-->
            <ul class="navbar-nav ml-auto">
                <?php foreach($menu as $key => $value): ?>

                    <li class="nav-item">
                        <a class="nav-link text-primary"
                           href="<?=$value['href']?>"
                            <?php if(strlen($value['href']) == 0): echo 'data-toggle="modal" data-target="#ModalLoginForm"'; endif; ?>
                        >
                            <?=$value['name']?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

    </nav>

    <div class="container" style="margin-top: 25px;">
        <div class="row">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin: 0 auto">
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="images/bee1.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="images/bee2.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="images/bee3.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        </div>

        <div clss="row" style="margin-top: 75px;">
            <div class="card-deck">
                <div class="card">
                    <img class="card-img-top" src="images/web.jpg" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">Webové rozhranie</h4>
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
                <div class="card">
                    <img class="card-img-top" src="images/phone.jpg" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">Mobilná aplikácia</h4>
                        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                    </div>

                </div>
                <div class="card">
                    <img class="card-img-top" src="images/hive.jpg" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">Meracie zariadenia</h4>
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                    </div>
                </div>
            </div>>
        </div>

    </div>

        <!-- Modal HTML Markup -->
    <div id="ModalLoginForm" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title text-xs-center">Prihlásenie</h4>
                </div>
                <div class="modal-body">
                    <form role="form" id = "login">
                        <div class="form-group">
                            <label class="control-label">Email</label>
                            <div>
                                <input type="email" class="form-control input-lg" name="email" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Heslo</label>
                            <div>
                                <input type="password" class="form-control input-lg" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember"> Zapamätaj si
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <a class="btn btn-link" href="">Zabudli ste heslo?</a>
                                <button type="button" id = "login_button" class="btn btn-info btn-block">Prihlásiť sa</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer text-xs-center">
                    Nemáte účet? <br><a href="/public/register"> Zaregistrujte sa »</a>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


    <?php echo $footer;?>

        <!-- Optional JavaScript -->

        <script src="js/jquery.min.js"></script>
        <script src="js/tether.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/slider.js"></script>
        <script src="js/slider_lr.js"></script>
        <script src="js/style.js"></script>
    </body>
</html>
