<?php
	$errName ="";
    $errMessage ="";
	$errAddress ="";

	if (isset($_POST['submit'])) {
		$id=$_COOKIE['user_id'];
		$name = $_POST['name'];
		$address = $_POST['address'];
		$message = $_POST['message'];
		$sms = 0;
		$email = 0;
		
		if (isset($_POST['e-mail'])) 
		{
			$email=true;
		}
		
		if (isset($_POST['sms'])) 
		{
			$sms=true;
		}
	
		if (!preg_match("/^[a-zA-Z á Á ä č Č ď Ď dž Dž é É í ĺ ľ Ľ ó Ó ó š Š ť Ť ú Ú ň Ň ý ž Ž ]*$/",$name) || (!$_POST['name'])) {
			$errName = "Zadali ste nesprávny formát mena! (príklad: Pekný úlik)!";
		}
		
		if (!preg_match("/^[a-zA-Z 0-9 á ä č Č ď Ď dž Dž é í ĺ ľ Ľ ó š Š ť Ť ú ň Ň ý ž Ž , ]*$/",$address) || (!$_POST['address'])) {
			$errAddress = "Zadali ste nesprávny formát adresy! (príklad: Lesnícka 44, Bratislava)"; 
		}
			
	
	if (!$errName && !$errAddress)
	{
		$ma = "";
		$subject = 'Včeličky Team';
		$result = 'Žiadosť o potvrdení objednávky';
		$text = $_POST["message"];
		$ma = $_POST["mail"];
		$prem=0;
		$poa = '<html><body>';
		$poa .= '<table rules="all" style="border-color: #666;" cellpadding="10">';
		$poa .= "<tr style='background: #eee;'><td><strong>Meno úľa:</strong> </td><td>" . strip_tags($_POST['name']) . "</td></tr>";
		$poa .= "<tr><td><strong>Adresa úľa:</strong> </td><td>" . strip_tags($_POST['address']) . "</td></tr>";
		
		if (isset($_POST['e-mail'])) {
			$poa .= "<tr><td><strong>E-mail:</strong> </td><td>" . Nastavený . "</td></tr>";
		}
		
		else{
			$poa .= "<tr><td><strong>E-mail:</strong> </td><td>" . Nenastavený . "</td></tr>";
		}
		
		
		if (isset($_POST['sms'])) {
			$poa .= "<tr><td><strong>SMS:</strong> </td><td>" . Nastavené . "</td></tr>";
		}
		
		else{
			$poa .= "<tr><td><strong>SMS:</strong> </td><td>" . Nenastavené . "</td></tr>";
		}
		
		$poa .= "<tr><td><strong>Odkaz:</strong> </td><td>" . strip_tags($_POST['message']) . "</td></tr>";
		$poa .= "</table>";
		$poa .= "</body></html>";
		$headers  = "MIME-Version: 1.0" . PHP_EOL;
		$headers .= "Content-Type: text/html; charset=utf-8" . PHP_EOL;
		$headers .= "From: WEB-Včeličky Team" . PHP_EOL;
if ( Mail("sosnak.matus@gmail.com ", $result, $poa, $headers) )
{
	echo '<script language="javascript">';
	echo 'alert("Objednávka bola úspešne odoslaná!")';
	echo '</script>';	
	
	$host = "147.175.149.151"; 
	$user = "postgres"; 
	$pass = "smenajlepsi"; 
	$db = "tp"; 

	$con = pg_connect("host=$host dbname=$db user=$user password=$pass")
		or die("Could not connect to server\n"); 

	$query = "INSERT INTO bees.orders VALUES ($id, '$name', '$address', '$message', '$sms', '$email', 'False');"; 
		$rs = pg_query($con, $query) or die("Cannot execute query: $query\n");
		pg_close($con); 	
	$_POST = array();
}
else 
{
	echo '<script language="javascript">';
	echo 'alert("Nastala neočakávaná chyba, na jej odstránení sa pracuje! Ospravedlňujeme sa.")';
	echo '</script>';
}
		
    }
		
  }
?>

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bee Manager</title>
    <meta name="description" content="BeeAdmin portal - Hive detail">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="..public/images/avicon.ico">
    <link rel="icon" href="..public/images/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom Theme Style -->
    <link href="../public/css/portal.css" rel="stylesheet">
    <link rel="stylesheet" href="../public/css/font-awesome.min.css">
    <link rel="stylesheet" href="../public/css/themify-icons.css">
    <link rel="stylesheet" href="../public/css/cs-skin-elastic.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>


<!-- Left Panel -->

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="../public/portal"><img src="../public/images/logo_portal1.png" alt="Logo"></a>
            <a class="navbar-brand hidden" href="../public/portal"><img src="../public/images/logo_portal2.png" alt="Logo"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="true" aria-label="Toggle navigation" id="toggler" style="visibility: hidden">
                <i class="fa fa-bars"></i>
            </button>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/BeeWebpage/public/portal"> <i class="menu-icon fa fa-dashboard"></i>Manažment úľov </a>
					<a href="/BeeWebpage/public/create_order"> <i class="menu-icon fa fa-dashboard"></i>Vytvorenie objednávky </a>
                    <a href="/BeeWebpage/public/notifications"> <i class="menu-icon fa fa-history"></i>Historia notifikácií</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->

    </nav>
</aside><!-- /#left-panel -->

<!-- Left Panel -->

<!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">

        <div class="header-menu">

            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="header-left">
                    <button class="search-trigger"><i class="fa fa-search"></i></button>
                    <div class="form-inline">
                        <form class="search-form">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                            <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                        </form>
                    </div>

                    <div class="dropdown for-notification">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-bell"></i>
                            <span class="count bg-danger">5</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="notification">
                            <p class="red">You have 3 Notification</p>
                            <a class="dropdown-item media bg-flat-color-1" href="#">
                                <i class="fa fa-check"></i>
                                <p>Server #1 overloaded.</p>
                            </a>
                            <a class="dropdown-item media bg-flat-color-4" href="#">
                                <i class="fa fa-info"></i>
                                <p>Server #2 overloaded.</p>
                            </a>
                            <a class="dropdown-item media bg-flat-color-5" href="#">
                                <i class="fa fa-warning"></i>
                                <p>Server #3 overloaded.</p>
                            </a>
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-sm-5">
                <div class="user-area dropdown float-right">		
				<?php 
							$id=$_COOKIE['user_name'];
										echo "<a>$id &ensp;</a>";
				?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="user-avatar rounded-circle" src="../public/images/admin.jpg" alt="User Avatar">
                    </a>

                    <div class="user-menu dropdown-menu">
                        <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                        <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                        <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                        <a class="nav-link" id="log_out_button" href="#"><i class="fa fa-power -off"></i>Logout</a>
                    </div>
                </div>

                <div class="language-select dropdown" id="language-select">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown"  id="language" aria-haspopup="true" aria-expanded="true">
                        <i class="flag-icon flag-icon-us"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="language" >
                        <div class="dropdown-item">
                            <span class="flag-icon flag-icon-fr"></span>
                        </div>
                        <div class="dropdown-item">
                            <i class="flag-icon flag-icon-es"></i>
                        </div>
                        <div class="dropdown-item">
                            <i class="flag-icon flag-icon-us"></i>
                        </div>
                        <div class="dropdown-item">
                            <i class="flag-icon flag-icon-it"></i>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </header><!-- /header -->

    <!--    Put content here:-->
    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
				 <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <h4><strong>Objednávací formulár</strong></h4>
                    <form action="" method="POST">
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" value="<?php if (isset($_POST['name'])){ echo htmlspecialchars($_POST['name']); } ?>" placeholder="Meno úľa" style="margin-top: 10px;" type="text">
							<?php echo "<p class='text-danger'>$errName</p>";?>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="address" value="<?php if (isset($_POST['address'])){ echo htmlspecialchars($_POST['address']); } ?>" placeholder="Adresa úľa">
							<?php echo "<p class='text-danger'>$errAddress</p>";?>
                        </div>
						<label>Notifikácie chcem dostávať na:</label>
						<br>
						<div class="form-check form-check-inline">
							<input class="form-check-input" type="checkbox" id="inlineCheckbox1" name="sms" value="option1">
							<label class="form-check-label" for="inlineCheckbox1">SMS</label>
						</div>
						<div class="form-check form-check-inline">
								<input class="form-check-input" type="checkbox" id="inlineCheckbox2" name="e-mail" value="option2">
								<label class="form-check-label" for="inlineCheckbox2">E-MAIL</label>
						</div>
						<br>
                        <div class="form-group" style="padding-top: 10px;">
                            <textarea class="form-control" name="message" rows="3" placeholder="Požiadavky"></textarea>
                        </div>
                       <button class="btn btn-default" type="submit" name="submit" style="border-color: black;">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i> Odoslať
                    </form>
                </div>
				<div class="col-md-7">
					<img src="/BeeWebpage/public/images/bee0.jpg" class="img-rounded" alt="Cinque Terre" style="/*! margin-right: -10px; */width: 100%;height: auto;">
                </div>
            </div>
        </div>
    </section>
                    
                </div>
            </div>
        </div>

</div> <!-- .content -->
</div><!-- /#right-panel -->

<!-- Right Panel -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
<script src="../public/js/jquery.min.js"></script>
<script src="../public/js/tether.min.js"></script>
<script src="../public/js/jquery.jeditable.js"></script>
<script src="../public/js/portal.js"></script>
<script src="../public/js/portal_main.js"></script>
<script src="./../node_modules/moment-with-locales-es6/node_modules/moment/min/moment-with-locales.min.js"></script>
<script src="js/notifications.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>



<!--<script src="../js/data-table/datatables-init.js"></script>-->

</body>
</html>
