<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="shortcut icon" href="images/avicon.ico">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/global.css">
    <link rel="stylesheet" href="css/register.css">
</head>
<body>

<!--Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top bg-faded">
    <a href="/BeeWebpage/public" class="navbar-brand text-primary" id="logo" style="margin-left: 10%">
        <img src="images/logo.png" width="50px" height="50px">
    </a>

    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <!--                        <ul class="navbar-nav">-->
        <ul class="navbar-nav ml-auto">
            <?php foreach($menu as $key => $value): ?>

                <li class="nav-item">
                    <a class="nav-link"
                       href="<?=$value['href']?>"
                        <?php if(strlen($value['href']) == 0): echo 'data-toggle="modal" data-target="#ModalLoginForm"'; endif; ?>
                    >
                        <?=$value['name']?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

</nav>

    <div class="container"style="margin: auto; max-width: 300px;">
        <div class="row">
<!--            <div class="panel panel-primary register-panel">-->
<!--                <div class="panel-body">-->
                    <form role="form" id = "register">
                        <div class="form-group" style="margin-top: 20px">
                            <h2>Registrácia</h2>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="signupName">* Vaše meno</label>
                            <input name="signupName" id="signupName" type="text" placeholder="Michal Novák" maxlength="50" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="signupEmail">* Email</label>
                            <input name="signupEmail" id="signupEmail" type="email" maxlength="50" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="signupEmailagain">* Zopakovať email</label>
                            <input name="signupEmailagain" id="signupEmailagain" type="email" maxlength="50" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="signupTelnumber">* Telefónne číslo</label>
                            <input
                                    name="signupTelnumber" id="signupTelnumber"
                                    type="text" maxlength="16"
                                    placeholder="+421 123 456 789"
                                    class="form-control"
                            >
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="signupPassword">* Heslo</label>
                            <input name="signupPassword" id="signupPassword" type="password" maxlength="25" class="form-control" placeholder="minimalne 8 znakov" length="40">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="signupPasswordagain">* Zopakovať heslo</label>
                            <input name="signupPasswordagain" id="signupPasswordagain" type="password" maxlength="25" class="form-control">
                        </div>
                        <div class="form-group">
                            <button type="submit" id="register_button" class="btn btn-info btn-block">Vytvorit účet</button>
                        </div>
                        <hr>
                        <p>Už máte účet? <a href="#" data-toggle="modal" data-target="#ModalLoginForm">Prihlásenie</a></p>
                    </form>
<!--                </div>-->
<!--            </div>-->
        </div>

    </div>

<!-- Modal HTML Markup -->
<div id="ModalLoginForm" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-xs-center">Prihlásenie</h4>
            </div>
            <div class="modal-body">
                <form id = "login" role="form" action="#">
                    <div class="form-group">
                        <label class="control-label">Email</label>
                        <div>
                            <input id="input-email" type="email" class="form-control input-lg" name="email" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Heslo</label>
                        <div>
                            <input type="password" class="form-control input-lg" name="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="remember"> Zapamätaj si
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            <a class="btn btn-link" href="">Zabudli ste heslo?</a>
                            <button type="button" id = "login_button" class="btn btn-info btn-block">Prihlásiť sa</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer text-xs-center">
                Nemáte účet? <br><a href="/auth/register"> Zaregistruj sa »</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<?php echo $footer;?>

<!-- Optional JavaScript -->
<script>
	function teamphoto() {	
		//window.location = "https://stackoverflow.com/";
		//window.location.href="http://stackoverflow.com";
		window.location = "https://team20-17.studenti.fiit.stuba.sk/#tim";
	 }
</script>

<script src="js/jquery.min.js"></script>
<script src="js/tether.min.js"></script>
<script src="js/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="js/form_validate.js"></script>
<script src="js/style.js"></script>
</body>
</html>
